{% set name = "apache-airflow-providers-presto" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-presto-{{ version }}.tar.gz
  sha256: cc94d198c86cfa290c2031aa1b5b018b3bb19d269a51c26c0f76b152a94885dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - pandas >=0.17.1,<1.4
    - presto-python-client >=0.7.0,<0.8

test:
  imports:
    - airflow.providers.presto
    - airflow.providers.presto.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Presto for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
