{% set name = "apache-airflow-providers-presto" %}
{% set version = "5.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_presto-{{ version }}.tar.gz
  sha256: 94c4990fd989a2eef1108a81c1edbee7863fa48353f6d81ff8511e68580982d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.6.0
    - pandas >=1.2.5,<2.2
    - presto-python-client >=0.8.4

test:
  imports:
    - airflow.providers.presto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-presto for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/presto/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
