{% set name = "apache-airflow-providers-presto" %}
{% set version = "5.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_presto-{{ version }}.tar.gz
  sha256: 5a3c543aba2a144278685e175dd3d8dc800411b905f9d7599d1f329840e2cbe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-common-sql >=1.26.0
    - presto-python-client >=0.8.4
    # more restrictive for python >=3.13
    - pandas >=2.2.3
    # more restrictive for python >=3.13
    - psycopg2-binary >=2.9.10

test:
  imports:
    - airflow.providers.presto
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-presto for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
