{% set name = "apache-airflow-providers-presto" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_presto-{{ version }}.tar.gz
  sha256: 3fd0c575716de4689797cbff41fd1efe3de72dcde6ccd6862ee09d5739b31013

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    - pandas >=2.1.2,<2.2
    - presto-python-client >=0.8.4

test:
  imports:
    - airflow.providers.presto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-presto for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/presto/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
