context:
  name: apache-airflow-providers-presto
  version: 5.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_presto-${{ version }}.tar.gz
  sha256: eef14b57bca62f9d43ac1f1c2aeb5def672862c0babce9c5e3cb0a1b8d6f72fd

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.12.0
    - apache-airflow-providers-common-sql >=1.32.0
    - presto-python-client >=0.8.4
    # tightest of upstream's floors (python >=3.14)
    - pandas >=2.3.3
    # tightest of upstream's floors (python >=3.13)
    - psycopg2-binary >=2.9.10
tests:
  - python:
      imports:
        - airflow.providers.presto
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-presto for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-presto/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
